AWSTemplateFormatVersion: 2010-09-09
Resources:
 DataBucket:
   Type: ‘AWS::S3::Bucket’
   Properties:
     BucketName: !Sub ‘${AWS::StackName}-pipeline-data’
     VersioningConfiguration:
       Status: Enabled